apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-deployment
spec:
  selector:
    matchLabels:
      app: bear
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: bear
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear

        ports:
        - containerPort: 80
