apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-deployment
spec:
  selector:
    matchLabels:
      app: moose
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: animal
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose

        ports:
        - containerPort: 80
