apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: animal
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: animal-persistent-storage
      mountPath: /tmp
  - name: music
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: animal-persistent-storage
      mountPath: /tmp/
  volumes:
  - name: animal-persistent-storage
    hostpath:
      path: /tmp/files/
