apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
  - name: redis
    image: redis:5.0.4
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /app/data
  volumes:
  - name: redis-persistent-storage
    emptyDir: {}
