kind: Service # Create service     
apiVersion: v1
metadata:
  name: animals-srv
spec:
  selector:
    app: animals  # Run on any pod with nginx label
  ports:          # Map ports
  - name: http    # Multiple ports listterns
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
